package OOPSCONCEPT;  //create package//

public interface USbank {
  int min_balace=100;
    public void debit();
}
 //IMP: NO METHOD BODY ONLY METHOD DECLARETION//
//IMP. WE CAN NOT CREATE OBJECT IN INTERFACE//
 // NO STATIC METHOD ALLOW//
 // YOU CAN DECLARE THE VARIABLE IN INTERFACE.ITS CALLED INTERAFACE VARIABLE//
// INTERFACE VARIABLES ARE STATIC IN NATURE AS A DEFAULT//